---
  extends: coveo
  parserOptions:
    ecmaVersion: 5
    sourceType: 'script'
  env:
    node: true
  globals:
    describe: true
    it: true
  rules:
    # override coveo default rules
    class-method-use-this: 0
    no-var: 0
    id-length: 0
    object-curly-spacing:
      - 2
      - always
      - objectsInObjects: false
    no-console: 0
